// Auto-generated by scripts/generate-content.mjs — do not edit manually

export const sidebar = [
  {
    label: "Model Architecture",
    items: [
    { label: "Litgpt", slug: "01-model-architecture/implementing-llms-litgpt" },
    { label: "Mamba", slug: "01-model-architecture/mamba-architecture" },
    { label: "Nanogpt", slug: "01-model-architecture/nanogpt" },
    { label: "RWKV", slug: "01-model-architecture/rwkv-architecture" },
    { label: "Torchtitan", slug: "01-model-architecture/distributed-llm-pretraining-torchtitan" }
    ]
  },
  {
    label: "Tokenization",
    items: [
    { label: "Huggingface Tokenizers", slug: "02-tokenization/huggingface-tokenizers" },
    { label: "Sentencepiece", slug: "02-tokenization/sentencepiece" }
    ]
  },
  {
    label: "Fine-Tuning",
    items: [
    { label: "Axolotl", slug: "03-fine-tuning/axolotl" },
    { label: "Llama Factory", slug: "03-fine-tuning/llama-factory" },
    { label: "PEFT", slug: "03-fine-tuning/peft-fine-tuning" },
    { label: "Unsloth", slug: "03-fine-tuning/unsloth" }
    ]
  },
  {
    label: "Mechanistic Interpretability",
    items: [
    { label: "Nnsight", slug: "04-mechanistic-interpretability/nnsight-remote-interpretability" },
    { label: "Pyvene", slug: "04-mechanistic-interpretability/pyvene-interventions" },
    { label: "Saelens", slug: "04-mechanistic-interpretability/sparse-autoencoder-training" },
    { label: "Transformer Lens", slug: "04-mechanistic-interpretability/transformer-lens-interpretability" }
    ]
  },
  {
    label: "Data Processing",
    items: [
    { label: "NEMO Curator", slug: "05-data-processing/nemo-curator" },
    { label: "Ray Data", slug: "05-data-processing/ray-data" }
    ]
  },
  {
    label: "Post-Training",
    items: [
    { label: "GRPO RL Training", slug: "06-post-training/grpo-rl-training" },
    { label: "Miles", slug: "06-post-training/miles-rl-training" },
    { label: "Openrlhf", slug: "06-post-training/openrlhf-training" },
    { label: "Simpo", slug: "06-post-training/simpo-training" },
    { label: "Slime", slug: "06-post-training/slime-rl-training" },
    { label: "Torchforge", slug: "06-post-training/torchforge-rl-training" },
    { label: "TRL Fine Tuning", slug: "06-post-training/fine-tuning-with-trl" },
    { label: "Verl", slug: "06-post-training/verl-rl-training" }
    ]
  },
  {
    label: "Safety & Alignment",
    items: [
    { label: "Constitutional Ai", slug: "07-safety-alignment/constitutional-ai" },
    { label: "Llamaguard", slug: "07-safety-alignment/llamaguard" },
    { label: "NEMO Guardrails", slug: "07-safety-alignment/nemo-guardrails" },
    { label: "Prompt Guard", slug: "07-safety-alignment/prompt-guard" }
    ]
  },
  {
    label: "Distributed Training",
    items: [
    { label: "Accelerate", slug: "08-distributed-training/huggingface-accelerate" },
    { label: "Deepspeed", slug: "08-distributed-training/deepspeed" },
    { label: "Megatron Core", slug: "08-distributed-training/training-llms-megatron" },
    { label: "Pytorch Fsdp2", slug: "08-distributed-training/pytorch-fsdp2" },
    { label: "Pytorch Lightning", slug: "08-distributed-training/pytorch-lightning" },
    { label: "Ray Train", slug: "08-distributed-training/ray-train" }
    ]
  },
  {
    label: "Infrastructure",
    items: [
    { label: "Lambda Labs", slug: "09-infrastructure/lambda-labs-gpu-cloud" },
    { label: "Modal", slug: "09-infrastructure/modal-serverless-gpu" },
    { label: "Skypilot", slug: "09-infrastructure/skypilot-multi-cloud-orchestration" }
    ]
  },
  {
    label: "Optimization",
    items: [
    { label: "AWQ", slug: "10-optimization/awq-quantization" },
    { label: "Bitsandbytes", slug: "10-optimization/quantizing-models-bitsandbytes" },
    { label: "Flash Attention", slug: "10-optimization/optimizing-attention-flash" },
    { label: "GGUF", slug: "10-optimization/gguf-quantization" },
    { label: "GPTQ", slug: "10-optimization/gptq" },
    { label: "HQQ", slug: "10-optimization/hqq-quantization" },
    { label: "Ml Training Recipes", slug: "10-optimization/ml-training-recipes" }
    ]
  },
  {
    label: "Evaluation",
    items: [
    { label: "Bigcode Evaluation Harness", slug: "11-evaluation/evaluating-code-models" },
    { label: "Lm Evaluation Harness", slug: "11-evaluation/evaluating-llms-harness" },
    { label: "NEMO Evaluator", slug: "11-evaluation/nemo-evaluator-sdk" }
    ]
  },
  {
    label: "Inference & Serving",
    items: [
    { label: "Llama Cpp", slug: "12-inference-serving/llama-cpp" },
    { label: "SGLANG", slug: "12-inference-serving/sglang" },
    { label: "Tensorrt LLM", slug: "12-inference-serving/tensorrt-llm" },
    { label: "VLLM", slug: "12-inference-serving/serving-llms-vllm" }
    ]
  },
  {
    label: "MLOps",
    items: [
    { label: "Mlflow", slug: "13-mlops/mlflow" },
    { label: "Swanlab", slug: "13-mlops/experiment-tracking-swanlab" },
    { label: "Tensorboard", slug: "13-mlops/tensorboard" },
    { label: "Weights And Biases", slug: "13-mlops/weights-and-biases" }
    ]
  },
  {
    label: "Agents",
    items: [
    { label: "A Evolve", slug: "14-agents/evolving-ai-agents" },
    { label: "Autogpt", slug: "14-agents/autogpt-agents" },
    { label: "Crewai", slug: "14-agents/crewai-multi-agent" },
    { label: "Langchain", slug: "14-agents/langchain" },
    { label: "Llamaindex", slug: "14-agents/llamaindex" }
    ]
  },
  {
    label: "RAG",
    items: [
    { label: "Chroma", slug: "15-rag/chroma" },
    { label: "Faiss", slug: "15-rag/faiss" },
    { label: "Pinecone", slug: "15-rag/pinecone" },
    { label: "Qdrant", slug: "15-rag/qdrant-vector-search" },
    { label: "Sentence Transformers", slug: "15-rag/sentence-transformers" }
    ]
  },
  {
    label: "Prompt Engineering",
    items: [
    { label: "Dspy", slug: "16-prompt-engineering/dspy" },
    { label: "Guidance", slug: "16-prompt-engineering/guidance" },
    { label: "Instructor", slug: "16-prompt-engineering/instructor" },
    { label: "Outlines", slug: "16-prompt-engineering/outlines" }
    ]
  },
  {
    label: "Observability",
    items: [
    { label: "Langsmith", slug: "17-observability/langsmith-observability" },
    { label: "Phoenix", slug: "17-observability/phoenix-observability" }
    ]
  },
  {
    label: "Multimodal",
    items: [
    { label: "Audiocraft", slug: "18-multimodal/audiocraft-audio-generation" },
    { label: "BLIP 2", slug: "18-multimodal/blip-2-vision-language" },
    { label: "CLIP", slug: "18-multimodal/clip" },
    { label: "Cosmos Policy", slug: "18-multimodal/evaluating-cosmos-policy" },
    { label: "LLAVA", slug: "18-multimodal/llava" },
    { label: "Openpi", slug: "18-multimodal/fine-tuning-serving-openpi" },
    { label: "Openvla Oft", slug: "18-multimodal/fine-tuning-openvla-oft" },
    { label: "Segment Anything", slug: "18-multimodal/segment-anything-model" },
    { label: "Stable Diffusion", slug: "18-multimodal/stable-diffusion-image-generation" },
    { label: "Whisper", slug: "18-multimodal/whisper" }
    ]
  },
  {
    label: "Emerging Techniques",
    items: [
    { label: "Knowledge Distillation", slug: "19-emerging-techniques/knowledge-distillation" },
    { label: "Long Context", slug: "19-emerging-techniques/long-context" },
    { label: "Model Merging", slug: "19-emerging-techniques/model-merging" },
    { label: "Model Pruning", slug: "19-emerging-techniques/model-pruning" },
    { label: "MOE Training", slug: "19-emerging-techniques/moe-training" },
    { label: "Speculative Decoding", slug: "19-emerging-techniques/speculative-decoding" }
    ]
  },
  {
    label: "ML Paper Writing",
    items: [
    { label: "Academic Plotting", slug: "20-ml-paper-writing/academic-plotting" },
    { label: "Ml Paper Writing", slug: "20-ml-paper-writing/ml-paper-writing" },
    { label: "Presenting Conference Talks", slug: "20-ml-paper-writing/presenting-conference-talks" },
    { label: "Systems Paper Writing", slug: "20-ml-paper-writing/systems-paper-writing" }
    ]
  },
  {
    label: "Research Ideation",
    items: [
    { label: "Brainstorming Research Ideas", slug: "21-research-ideation/brainstorming-research-ideas" },
    { label: "Creative Thinking For Research", slug: "21-research-ideation/creative-thinking-for-research" }
    ]
  }
];
